import type { Metadata } from "next";
import { Inter } from "next/font/google";
// @ts-expect-error: allow side-effect import of global CSS without type declarations
import "./globals.css";
import MainHeader from "@/components/MainHeader";
import { Providers } from "./provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased dark`}
      >
        <Providers>
          <div className="container max-w-2xl m-auto dark:bg-transparent p-4">
            <MainHeader />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
